### PR TITLE
Added json schema for validating manifests

### PR DESCRIPTION
**Pull request by aish-where-ya**
## Primary reviewer
@lachieh @brooksmtownsend 

## Feature or Problem
FEAT : A[ json schema](https://json-schema.org) for validating the format of manifests

## Related Issues
#122 #123 #176 

## Release Information
next

## Consumer Impact
Incorrect manifests would be rejected by the system

## Testing
All test cases for current manifests pass. Also validated against an [online validator](https://www.jsonschemavalidator.net).

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
NA

### Acceptance or Integration
NA

### Manual Verification
manually verified

### CODE REVIEW

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
Looks good in terms of where we're validating and validating the manifest, added a few requests to just ensure we're including the JSON schema at compile time and compiling it only once instead of on each `put`. 

I optionally included some more restrictions that we could put on the `oam` format since we aren't using scopes and variables today, but it's great to know that those exist. Feel free to dismiss those comments if you disagree!

**Comment by aish-where-ya** [comment]
Added an additional test case for incorrect manifests so that it displays the correct error message.
This is how the error messages look like if they parse correctly but have incorrect elements:
```
Validation Error : 
Validation error in object: {"name":"ui","properties":{"image":"wasmcloud.azurecr.io/ui:0.3.2"},"traits":[{"properties":{"spread":[{"name":"uiclinicapp","requirements":{"app":"petclinic"}}]},"type":"spreadscaler"}],"type":"actor"} 
Object path: /spec/components/0
```

**Comment by aish-where-ya** [comment]
Tried out other error reporting variants available in the JSON Schema [ValidationError](https://docs.rs/jsonschema/latest/jsonschema/error/struct.ValidationError.html) struct. The `kind` and `schema_path` options are not that descriptive and users will have to cross check with the OAM validation schema to find the errors in their manifest. Currently `instance` and `instance_path` give a descriptive idea of the error.

The only thought pending is that these descriptive errors should be enough for the UI. @lachieh please refer the previous comment for the descriptiveness of the errors. Feel free to review and make suggestions that I can incorporate into this PR.

**Review by brooksmtownsend — DISMISSED** [review]

**Comment by brooksmtownsend** [comment]
Closing in favor of #184

**Pull request closed without merging**
